// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core.Services {

  /// <summary>Holder for reflection information generated from config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb25maWcucHJvdG8SCmNvcmUucHJvdG8aHmdvb2dsZS9wcm90b2J1Zi93",
            "cmFwcGVycy5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGhVj",
            "b25maWdfbWVzc2FnZXMucHJvdG8yvgIKBkNvbmZpZxI0CgpHZXRTZXR0aW5n",
            "EhAuY29yZS5jb25maWcuS2V5GhQuY29yZS5jb25maWcuU2V0dGluZxJBCgpB",
            "ZGRTZXR0aW5nEhcuY29yZS5jb25maWcuU2V0U2V0dGluZxoaLmdvb2dsZS5w",
            "cm90b2J1Zi5Cb29sVmFsdWUSQAoNR2V0VXNlckNvbmZpZxIWLmdvb2dsZS5w",
            "cm90b2J1Zi5FbXB0eRoXLmNvcmUuY29uZmlnLkNvbmZpZ0Jsb2ISPAoKUmVz",
            "ZXRDYWNoZRIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90",
            "b2J1Zi5FbXB0eRI7Cg5HZXRHcm91cENvbmZpZxIQLmNvcmUuY29uZmlnLktl",
            "eRoXLmNvcmUuY29uZmlnLkNvbmZpZ0Jsb2JCEKoCDUNvcmUuU2VydmljZXNi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Core.Common.ConfigMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
