// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: config.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Core.Services {

  /// <summary>Holder for reflection information generated from config.proto</summary>
  public static partial class ConfigReflection {

    #region Descriptor
    /// <summary>File descriptor for config.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConfigReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxjb25maWcucHJvdG8SCmNvcmUucHJvdG8aFWNvbmZpZ19tZXNzYWdlcy5w",
            "cm90bzLQAwoGQ29uZmlnEkQKCkdldFNldHRpbmcSGi5jb3JlLmNvbmZpZy5H",
            "ZXRTZXR0aW5nUmVxGhouY29yZS5jb25maWcuR2V0U2V0dGluZ1JlcxJECgpB",
            "ZGRTZXR0aW5nEhouY29yZS5jb25maWcuU2V0U2V0dGluZ1JlcRoaLmNvcmUu",
            "Y29uZmlnLlNldFNldHRpbmdSZXMSTQoNR2V0VXNlckNvbmZpZxIdLmNvcmUu",
            "Y29uZmlnLkdldFVzZXJDb25maWdSZXEaHS5jb3JlLmNvbmZpZy5HZXRVc2Vy",
            "Q29uZmlnUmVzEkQKClJlc2V0Q2FjaGUSGi5jb3JlLmNvbmZpZy5SZXNldENh",
            "Y2hlUmVxGhouY29yZS5jb25maWcuUmVzZXRDYWNoZVJlcxJQCg5HZXRHcm91",
            "cENvbmZpZxIeLmNvcmUuY29uZmlnLkdldEdyb3VwQ29uZmlnUmVxGh4uY29y",
            "ZS5jb25maWcuR2V0R3JvdXBDb25maWdSZXMSUwoPQWRkR3JvdXBTZXR0aW5n",
            "Eh8uY29yZS5jb25maWcuU2V0R3JvdXBTZXR0aW5nUmVxGh8uY29yZS5jb25m",
            "aWcuU2V0R3JvdXBTZXR0aW5nUmVzQhCqAg1Db3JlLlNlcnZpY2VzYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Core.Entities.ConfigMessagesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
